### ISSUE TITLE
Missing update on multiple association between same models

### ISSUE THREAD

**Issue by MrStanDu33** [sequelize/website#475]
### What was unclear/insufficient/not covered in the documentation

In **Sequelize v7** documentation, under the [`associations` category](https://sequelize.org/docs/v7/core-concepts/assocs/), a snippet is given to demonstrate how to define multiple associations from a model A to a model B [here](https://sequelize.org/docs/v7/core-concepts/assocs/#multiple-associations-involving-the-same-models).

this is the snippet :
```js
Team.hasOne(Game, { as: 'HomeTeam', foreignKey: 'homeTeamId' });
Team.hasOne(Game, { as: 'AwayTeam', foreignKey: 'awayTeamId' });
Game.belongsTo(Team);
```

This example always worked, but since [`v7.0.0-alpha.14`](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.14), this is not the case anymore.

I cannot find what specifically causes this to crash, but the thing is that, now, this code throws an error :
![image](https://github.com/sequelize/website/assets/22714562/f5ac3cef-a711-4094-9518-0e75abc5b8db)

### If possible: Provide some suggestion on how we can enhance the docs

I can not find what is precisely guilty in the changes between [`v7.0.0-alpha.14`](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.14) and [`v7.0.0-alpha.13`](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.13) (a lot of code has been updated 🫤)

But I tried every versions from [`v7.0.0-alpha.14`](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.14) to [`v7.0.0-alpha.26`](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.26), and this snippet never worked. So IO think something changed, but this thing is causing breaking changes.

Unfortunatly, there is no mentions of this breaking change in the [upgrade guide for Sequelize v7](https://sequelize.org/docs/v7/other-topics/upgrade/), and I think that it should be important to note this change (and update accordingly the [`associations` category](https://sequelize.org/docs/v7/core-concepts/assocs/#multiple-associations-involving-the-same-models) documentation.)

### Additional context

I found out this bug while digging a bit deeper on [this issue](https://github.com/sequelize/sequelize/issues/16007)

**Comment by ephys** [comment]
I've provided a response about this on https://github.com/sequelize/sequelize/issues/16007, but for more info:

This is the PR you're looking for: https://github.com/sequelize/sequelize/pull/14280

The issues you're facing is caused by the following breaking changes: 
- https://sequelize.org/docs/v7/other-topics/upgrade/#associations-names-are-now-unique 
- and here https://sequelize.org/docs/v7/other-topics/upgrade/#bidirectional-association-options

I'll keep this open to add an explicit note about how to declare two associations that reference the same model in our guides & breaking changes
