### ISSUE TITLE
Titles of some pages are not styled

### ISSUE THREAD

**Issue by WikiRik** [sequelize/website#56]
As the image below shows some page titles are expected (like 'Model Basics'), but others are their filename ('getters-setters-virtuals')
![image](https://user-images.githubusercontent.com/13023439/161441843-f3c4c3fc-6c2d-4e1d-8574-52e1b1f6c1ee.png)

**Comment by ephys** [comment]
Docusaurus is supposed to use the first h1 of each page as the page title.
This used to work, then it failed in github pages but work locally, now it fails everywhere.
I'm thinking a docusaurus update broke something?

As a workaround, we can use the `title` property in the document's metadata, instead of a h1 - like we did in intro.mdx:

![image](https://user-images.githubusercontent.com/1280915/161485509-eae000b9-7479-417b-9d19-9c5cb0e2786c.png)
