### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by ephys** [sequelize/website#57]
Docusaurus supports searching through the documentation thanks to Agolia https://docusaurus.io/docs/search. Let's add that to our site :)

We already did talk about this in the initial PR but search wasn't a blocking point for the initial release because the previous esdoc search only searched through the API reference (which is still there)

**Comment by EyePulp** [comment]
Nice! I was wondering if Algolia was an option.  I didn't know if they had a pricing option that would fit the project.

**Comment by ronald-das** [comment]
Search functionality is need of the hour, it takes a long time to search through docs

**Comment by lucasgcbkhomp** [comment]
@WikiRik If you have the administration e-mail address can apply for Algolia here:

https://docsearch.algolia.com/apply/

Then all we need to do is add an environment variable to the [docusaurus config](https://github.com/sequelize/website/blob/main/docusaurus.config.js) according to their [documentation](https://docusaurus.io/docs/search#connecting-algolia), set it on netifly and voilá, usable docs for the world.


> Search functionality is need of the hour, it takes a long time to search through docs

The documentation is borderline unusable as it is. It's actually worse than a `.pdf` manual because one can easily search for relevant keywords in those. 

It's critical; not a single person I've introduced `sequelize` to appreciates the tool because of this fact: Learning anything about it is excruciating to a point people wish to use raw SQL because the docs for the databases themselves are more accessible.

I'd go as far as saying most of the userbase relies on indexed google results. If this project wishes for contributors and new users then it _needs_ this feature.
